<a href="https://colab.research.google.com/github/samalasathwika/Libraries/blob/main/MiniProjectUsingPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import  pandas as pd
job_market=pd.read_csv("/content/indian-job-market-dataset-2025.csv")


job_market

,title,jobId,currency,jobUploaded,companyName,tagsAndSkills,experience,salary,location,companyId,ReviewsCount,AggregateRating,jobDescription,minimumSalary,maximumSalary,minimumExperience,maximumExperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,NaN,NaN,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as F...",300000.0,500000.0,6.0,11.0
2,Opening For Performance Marketing - Chennai,270925007492,INR,6 Days Ago,TVS Credit Services Ltd,"Performance Marketing,User Acquisition,growth ...",12-18 Yrs,Not disclosed,Chennai,1324750,2892.0,4.2,MBA Marketing (preferred Tier II or III B- Sch...,0.0,0.0,12.0,18.0
3,Medical Billing Executive,270925007443,INR,6 Days Ago,GNR Global Services,"Fluent English,Spoken English,Good English Com...",0-3 Yrs,"70,000-2 Lacs PA","Mohali, Chandigarh, Kharar, Zirakpur",123804403,NaN,NaN,Job Title-Medical Billing Executive\nLocation-...,70000.0,200000.0,0.0,3.0
4,Senior Group Product Manager - CNS Therapy,270925007430,INR,6 Days Ago,Cadila Pharmaceuticals,"Product Marketing,CNS,Product Management,Nephr...",5-10 Yrs,8-18 Lacs PA,Ahmedabad,14957,2134.0,3.4,Principal Tasks & Responsibilities : (Please w...,800000.0,1800000.0,5.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97924,"CNC Machine Maintenance Engineer @ Manali, Che...",270925008790,INR,6 Days Ago,GSH Group,"CNC Maintenance,CNC Machines,Electrical Mainte...",2-5 Yrs,"50,000-2 Lacs PA","Chennai, Thiruvallur",938550,284.0,4.2,Experience: Minimum 2+ Years in CNC Machine El...,50000.0,200000.0,2.0,5.0
97925,IT Cum Digital Marketing Executive,270925008668,INR,6 Days Ago,Luxus Green Mobility Pvt. Ltd.,"Google AdWords,Digital Marketing,Social Media ...",1-2 Yrs,Not disclosed,Bilaspur,123904985,13.0,2.6,<p> </p><p><strong>Position Overview :-</stron...,0.0,0.0,1.0,2.0
97926,Senior Research Associate,270925008467,INR,6 Days Ago,Cadila Pharmaceuticals,"Analytical Method Validation,Analytical Method...",4-9 Yrs,Not disclosed,Ahmedabad,14957,2134.0,3.4,Documentation as per GLP requirement,0.0,0.0,4.0,9.0
97927,Customer Care Associate,270925008099,INR,6 Days Ago,GNR Global Services,"Fluent English,Spoken English,Strong Communica...",0-3 Yrs,"70,000-2 Lacs PA","Mohali, Chandigarh, Zirakpur",123804403,NaN,NaN,Job title-Customer Care Associate\nJob locatio...,70000.0,200000.0,0.0,3.0
97928,Client Relationship Executive,270925008094,INR,6 Days Ago,Logon Global Solutions,"Client Support,English,Client Coordination,Mal...",0-3 Yrs,1.92-3.36 Lacs PA,Kochi(Kakkanad),125008981,4.0,4.2,<p> <strong>Role:</strong> Primary advisor for...,192000.0,336000.0,0.0,3.0

In [3]:
#total job postings
job_market.value_counts()

title                                                          jobId         currency  jobUploaded  companyName                 tagsAndSkills                                                                                                                 experience  salary         location                                      companyId  ReviewsCount  AggregateRating  jobDescription                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    minimumSalary  maximumSalary  minimumExperience  maximumExperience
Branch Operations Manager-BRANCH BANKING-Service               230925502570  INR       10 Days Ago  Kotak Mahindra Bank         Front Office Staff,Customer service orientation,Branch banking,Branch operations,Banking,Management,KYC Compliance,RO system  3-8 Yrs     Not disclosed  Karimnagar                                    3389506    20307.0       3.7              Job Requirement:  . MBA / Graduate . <br><br>Minimum work exp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0.0            0.0            3.0                8.0                  2
Relationship Manager-LAP-Loan Against Property-Sales           250925500674  INR       8 Days Ago   Kotak Mahindra Bank         Direct sales,Loans,Direct marketing,Branch banking,Area sales,Banking,loan sales,Credit cards                                 3-8 Yrs     Not disclosed  Pune                                          3389506    20306.0       3.7               .  . Qualification - Graduate / MBA<br><br>Experience in SECURED LOAN SALES is Must<br><br>Minimum 3 years work experience in Home Loan /Mortgage Sales with DMA / DST/Bank Branches<br><br>Skills & Experience .  .                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             0.0            0.0            3.0                8.0                  2

In [7]:
#no.of unique companies that are hiring
job_market['companyName'].nunique()

18668

In [8]:
#no.ofunique job titles
job_market['title'].nunique()

55104

In [9]:
#columns contain missing values, and count
job_market.isnull().sum()

title                    0
jobId                    0
currency                 0
jobUploaded              0
companyName              4
tagsAndSkills          571
experience            2105
salary                   0
location                 0
companyId                0
ReviewsCount         35252
AggregateRating      35252
jobDescription           0
minimumSalary          571
maximumSalary          571
minimumExperience      571
maximumExperience      571
dtype: int64

In [10]:
#duplicate jobId values
job_market['jobId'].duplicated().sum()

np.int64(250)

In [17]:
#percentage of jobs that have salary information missing or undisclosed
(job_market['salary'] == 0).sum() / len(job_market) * 100

np.float64(0.0)

In [19]:
#What are the top 10 companies with the most job postings?
job_market['companyName'].value_counts().head(10)

companyName
Accenture                                8204
IDESLABS PRIVATE LIMITED                 2303
Wipro                                    1496
Krazy Mantra HR Solutions Pvt. Ltd       1028
Kotak Mahindra Bank                       987
PRO Hr Complete Solutions                 982
Infosys                                   938
Capgemini                                 700
IBM                                       687
PRADEEPIT CONSULTING SERVICES PVT LTD     618
Name: count, dtype: int64

In [20]:
#What are the top 10 most common job titles?
job_market['title'].value_counts().head(10)

title
Application Developer             2039
Application Lead                  1347
Sales Executive                    576
Software Development Engineer      497
Business Development Executive     457
Trust & Safety New Associate       348
Data Engineer                      339
Business Development Manager       323
Sales Manager                      319
Java Full Stack Developer          283
Name: count, dtype: int64

In [21]:
#Which 10 locations have the most job opportunities?
job_market['location'].value_counts().head(10)

location
Bengaluru      16823
Hyderabad       7669
Pune            6112
Chennai         4431
Gurugram        4233
Mumbai          4157
Noida           2695
Remote          1961
Ahmedabad       1726
Navi Mumbai     1453
Name: count, dtype: int64

In [28]:
#What is the average minimum and maximum salary across the dataset?
avg_min=job_market['minimumSalary'].mean()
avg_max=job_market['maximumSalary'].mean()
print(int(avg_min))
print(int(avg_max))

198309
318609

In [30]:
#Which job posting has the highest maximumSalary
highest_salary_job_index = job_market['maximumSalary'].idxmax()
highest_salary_job_title = job_market.loc[highest_salary_job_index, 'title']
print(f"The job posting with the highest maximum salary is: {highest_salary_job_title}")

The job posting with the highest maximum salary is: Deputy Manager

In [31]:
#Which companies offer the highest average maximum salary?
job_market.groupby('companyName')['maximumSalary'].mean().sort_values(ascending=False).head(1)

companyName
European Company    30000000.0
Name: maximumSalary, dtype: float64

In [35]:
#Which locations have the highest average salaries?
highest_avg_sal=job_market.groupby('location')['maximumSalary'].mean().sort_values(ascending=False).head(10)
highest_avg_sal

location
Tamil Nadu, Kerala                                30000000.0
Kashipur, Dhanbad, Ajmer                          15000000.0
Hyderabad, Kakinada                               15000000.0
Sirsa, Kolhapur, Moradabad                        10000000.0
Jabalpur, Central African Republic, Aurangabad    10000000.0
Ambikapur, Raigarh, Raipur                        10000000.0
Khambhat, Anand, Vadodara                         10000000.0
Indore, Bhandara, Durgapur                        10000000.0
Indore, Chennai, Bengaluru                        10000000.0
Durgapur, Central African Republic, Firozabad      9500000.0
Name: maximumSalary, dtype: float64

In [36]:
#What are the top 10 highest-paying jobs requiring 0–1 years of minimum experience?
job_market[job_market['minimumExperience'] == 0].sort_values(by='maximumSalary', ascending=False).head(10)

,title,jobId,currency,jobUploaded,companyName,tagsAndSkills,experience,salary,location,companyId,ReviewsCount,AggregateRating,jobDescription,minimumSalary,maximumSalary,minimumExperience,maximumExperience
7160,Urgent Requirement Medical Oncologist Doctors,260925032082,INR,6 Days Ago,Tech India,"Medical Oncology,Oncology,DM,Cancer,Medical,Re...",0-5 Yrs,90 Lacs-1.5 Cr PA,"Kashipur, Dhanbad, Ajmer",6144622,NaN,NaN,Both freshers and experienced specialists may ...,9000000.0,15000000.0,0.0,5.0
52413,Medical Oncologist Consultant,250925012828,INR,8 Days Ago,Amrach Consulting Services,"Medical Oncology,Medical Oncologist,Consulting...",0-5 Yrs,90 Lacs-1.25 Cr PA,Bareilly,123613231,NaN,NaN,II We are Hiring II. Medical Oncologist for Me...,9000000.0,12500000.0,0.0,5.0
9719,Medical Oncologist Consultant,300925926266,INR,3 Days Ago,Amrach Consulting Services,"Medical Oncology,Medical Oncologist,Consulting...",0-5 Yrs,90 Lacs-1.25 Cr PA,Bareilly,123613231,NaN,NaN,II We are Hiring II. Medical Oncologist for Me...,9000000.0,12500000.0,0.0,5.0
71252,Interventional Cardiologist For a Hospital in ...,230925038646,INR,10 Days Ago,Sigma Placement Consultancy,"Cardiologist,DNB Cardiology,Cardio,DM Cardiolo...",0-5 Yrs,85 Lacs-1.25 Cr PA,Firozpur,831563,NaN,NaN,A physician who treats and diagnoses disease a...,8500000.0,12500000.0,0.0,5.0
8676,Sales Manager,31025003334,INR,Today,Inframart Realtech India,"water dispenser sales,Corporate Gifts,Corporat...",0-3 Yrs,0-1.08 Cr PA,Bengaluru,124764499,17.0,3.9,<p>Responsibilities:</p><p>* Manage corporate ...,0.0,10800000.0,0.0,3.0
7157,Urgent Requirement of Cardiologists,260925032494,INR,6 Days Ago,Tech India,"Interventional Cardiology,Angiography,Angiopla...",0-5 Yrs,70 Lacs-1 Cr PA,"Sirsa, Kolhapur, Moradabad",6144622,NaN,NaN,Relevant experience in clinical or hospital se...,7000000.0,10000000.0,0.0,5.0
7716,Required Consultant Cardiologist,190625028315,INR,4 Days Ago,Sapna Hr Services,"Cardiology,Consulting",0-5 Yrs,40 Lacs-1 Cr PA,"Indore, Bhandara, Durgapur",1085476,NaN,NaN,<br /><p>Greetings From Sapna HR Services !!!<...,4000000.0,10000000.0,0.0,5.0
12180,Job Opening of Consultant Urologist,40625029374,INR,5 Days Ago,Sapna Hr Services,"Urology,Consulting",0-5 Yrs,35 Lacs-1 Cr PA,"Jabalpur, Central African Republic, Aurangabad",1085476,NaN,NaN,<p>Greetings From Sapna HR Services !!!</p><br...,3500000.0,10000000.0,0.0,5.0
10652,Opening For Hemato Oncologist Meerut Uttar Pr...,260925032205,INR,6 Days Ago,Tech India,"Hematology,Haematology,Immunology,Oncology,Cancer",0-5 Yrs,60 Lacs-1 Cr PA,"Ghaziabad, Meerut, Delhi / NCR",6144622,NaN,NaN,<p> </p><p> Opening for <strong>Hemato-Oncolog...,6000000.0,10000000.0,0.0,5.0
604,Cardiologist,150125014222,INR,2 Days Ago,Ang Placement And Staffing Solutions,"Cardiology,Pacemaker Implantation,Angioplasty,...",0-5 Yrs,60 Lacs-1 Cr PA,"Ambikapur, Raigarh, Raipur",1412850,NaN,NaN,"Cardiologist"". We are delighted to announce ex...",6000000.0,10000000.0,0.0,5.0

In [39]:
#How many jobs require zero minimum experience?
zero_min_experience_jobs = job_market[job_market['minimumExperience'] == 0]
num_zero_min_experience_jobs = len(zero_min_experience_jobs)
num_zero_min_experience_jobs

12393

In [40]:
#Find the top 20 most demanded skills in the Indian job market from tagsAndSkills
job_market['tagsAndSkills'].str.split(', ').explode().value_counts().head(20)

tagsAndSkills
Retail,Lead generation,Forex,Investment products,Sales,Customer satisfaction,Business Development Associate,Financial services                                              116
bde,cold calling,business development,business development management,financial services,corporate sales,sales,marketing                                                    110
customer service,creative writing,moderation,content writing,stress analysis,digital marketing,market research,content management                                            77
Loans,Networking,Branch banking,Relationship building,Anti money laundering,Customer service,Customer engagement,Internet banking                                            77
customer service,moderation,content writing,stress analysis,business process outsourcing,non voice process,market research,content management                                74
business loan,business development,sales,marketing,direct selling,channel sales,team handling,loan against property                                                          58
Object Oriented technology,TOGAF,J2EE technology,OBRM,Service-Oriented Architecture,C/C++,SOA,E-TOM Architecture                                                             52
Medical Coding,HCPCS,Clinical Research,CPT,Medical Transcription,CPC,ICD,Cpt Coding                                                                                          43
SAP ABAP,OData,SAP FICA,Adobe Forms,Smart Forms,collections,invoicing,SAP S/4HANA                                                                                            42
trade finance,sales,marketing,trade,secondary sales,foreign exchange,forex operations,import                                                                                 41
balance sheet,variance analysis,balance sheet reconciliation,record to report,accounts receivable,accounts payable,journal entries,general accounting                        40
relationship management,channel sales,channel management,mortgage loans,direct sales,loan against property,term loan,mortgage                                                40
C2C,Dice,W2,US Recruitment,US IT recruitment,IT recruitment,Recruitment                                                                                                      39
Er Studio,Data Modeling,ERwin,AWS,SQL,NoSQL,GCP,Data Architecture                                                                                                            37
SAP Yard logistics,Business Object Processing Framework,FSD Preparation,OData Services,Unit testing,BOPF,POWL Queries,ABAP                                                   37
C2C,Dice,W2,US Recruitment,IT recruitment,Recruitment,US IT recruitment                                                                                                      35
channel sales,business development,sales,marketing,direct sales,agency channel,distribution,corporate sales                                                                  34
SAP GRC,EAM,Security consulting,SAP BRM,SAP ARM,SAP S/4HANA security,SOX,GDPR                                                                                                34
SAP EM,SAP IBP Consultant,SAP Integrated Business Planning,SAP IBP Supply Planning,SAP IBP Demand Planning,SAP IBP Implementation,SAP IBP,SAP IBP Inventory Optimization     32
SAP ABAP HR,SAP,ABAP HR,test cases,Outbound interfaces,Inbound interfaces,S4HANA,Technical Specifications                                                                    32
Name: count, dtype: int64